-- ============================================================================
-- Bean Growers Australia — Fumigation Certificates schema
-- Paste this whole file into: Supabase dashboard -> SQL Editor -> New query.
-- Safe to re-run (uses IF NOT EXISTS / CREATE OR REPLACE).
-- ============================================================================

-- ── Certificates ──────────────────────────────────────────────────────────
-- cert_number is a human-friendly auto-incrementing number (1, 2, 3 ...).
-- The internal primary key stays a uuid.
create table if not exists public.certificates (
  id            uuid primary key default gen_random_uuid(),
  cert_number   bigint generated by default as identity,
  container_no  text not null,
  volume        numeric,
  fum_date      date not null,
  cert_date     date,
  release_date  date,
  avail_date    date,
  load_date     date,
  loaded_from   text default 'SHED',
  loaded_by     text,
  chep_count    integer,
  vent_period   text default '24 HOURS',
  created_by    uuid references auth.users (id) default auth.uid(),
  created_at    timestamptz not null default now()
);

create index if not exists certificates_container_idx on public.certificates (container_no);
create index if not exists certificates_created_idx on public.certificates (created_at desc);

-- ── Line items ─────────────────────────────────────────────────────────────
create table if not exists public.certificate_lines (
  id              uuid primary key default gen_random_uuid(),
  certificate_id  uuid not null references public.certificates (id) on delete cascade,
  line_no         text,
  count_text      text,
  bags            integer,
  domestic        boolean default false,
  export_flag     boolean default false,
  seed            boolean default false,
  comments        text,
  position        integer default 0
);

create index if not exists certificate_lines_cert_idx on public.certificate_lines (certificate_id);

-- ── Loaders (suggestions for the "Loaded By" field) ─────────────────────────
create table if not exists public.loaders (
  id    uuid primary key default gen_random_uuid(),
  code  text unique not null
);

insert into public.loaders (code)
values ('JW'), ('CM'), ('CMc'), ('PC'), ('NS'), ('LW')
on conflict (code) do nothing;

-- ============================================================================
-- Row Level Security
-- These are legal documents, so we lock everything to signed-in users only.
-- The public anon key cannot read or write once RLS is on with these policies.
-- ============================================================================
alter table public.certificates       enable row level security;
alter table public.certificate_lines  enable row level security;
alter table public.loaders            enable row level security;

-- Any authenticated user has full access. (Single-team internal tool.)
drop policy if exists "auth full access" on public.certificates;
create policy "auth full access" on public.certificates
  for all to authenticated using (true) with check (true);

drop policy if exists "auth full access" on public.certificate_lines;
create policy "auth full access" on public.certificate_lines
  for all to authenticated using (true) with check (true);

drop policy if exists "auth read loaders" on public.loaders;
create policy "auth read loaders" on public.loaders
  for select to authenticated using (true);

drop policy if exists "auth write loaders" on public.loaders;
create policy "auth write loaders" on public.loaders
  for all to authenticated using (true) with check (true);
